/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Quiz } from '../../models/quiz';

export interface GetQuizzesByCreatedAtQuery$Params {
  createdAt: string;
}

export function getQuizzesByCreatedAtQuery(http: HttpClient, rootUrl: string, params: GetQuizzesByCreatedAtQuery$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Quiz>>> {
  const rb = new RequestBuilder(rootUrl, getQuizzesByCreatedAtQuery.PATH, 'get');
  if (params) {
    rb.path('createdAt', params.createdAt, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Quiz>>;
    })
  );
}

getQuizzesByCreatedAtQuery.PATH = '/quiz/by-created-at-query/{createdAt}';
