/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Quiz } from '../../models/quiz';

export interface GetQuizzesByCreatedAtBetween$Params {
  start: string;
  end: string;
}

export function getQuizzesByCreatedAtBetween(http: HttpClient, rootUrl: string, params: GetQuizzesByCreatedAtBetween$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Quiz>>> {
  const rb = new RequestBuilder(rootUrl, getQuizzesByCreatedAtBetween.PATH, 'get');
  if (params) {
    rb.path('start', params.start, {});
    rb.path('end', params.end, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Quiz>>;
    })
  );
}

getQuizzesByCreatedAtBetween.PATH = '/quiz/by-created-at-between/{start}/{end}';
