/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TrainingResponse } from '../../models/training-response';

export interface FindTrainingById$Params {
  'training-id': number;
}

export function findTrainingById(http: HttpClient, rootUrl: string, params: FindTrainingById$Params, context?: HttpContext): Observable<StrictHttpResponse<TrainingResponse>> {
  const rb = new RequestBuilder(rootUrl, findTrainingById.PATH, 'get');
  if (params) {
    rb.path('training-id', params['training-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TrainingResponse>;
    })
  );
}

findTrainingById.PATH = '/Trainings/{training-id}';
