/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Training } from '../../models/training';

export interface UpdateTraining$Params {
  'training-id': number;
  training: Training;
}

export function updateTraining(http: HttpClient, rootUrl: string, params: UpdateTraining$Params, context?: HttpContext): Observable<StrictHttpResponse<Training>> {
  const rb = new RequestBuilder(rootUrl, updateTraining.PATH, 'patch');
  if (params) {
    rb.path('training-id', params['training-id'], {});
    rb.query('training', params.training, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Training>;
    })
  );
}

updateTraining.PATH = '/Trainings/updateTraining/{training-id}';
