/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CashFlows } from '../../models/cash-flows';

export interface AddCashFlows$Params {
      body: CashFlows
}

export function addCashFlows(http: HttpClient, rootUrl: string, params: AddCashFlows$Params, context?: HttpContext): Observable<StrictHttpResponse<CashFlows>> {
  const rb = new RequestBuilder(rootUrl, addCashFlows.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CashFlows>;
    })
  );
}

addCashFlows.PATH = '/api/finance/addCashFlows';
