/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Asset } from '../../models/asset';

export interface AddAsset$Params {
      body: Asset
}

export function addAsset(http: HttpClient, rootUrl: string, params: AddAsset$Params, context?: HttpContext): Observable<StrictHttpResponse<Asset>> {
  const rb = new RequestBuilder(rootUrl, addAsset.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Asset>;
    })
  );
}

addAsset.PATH = '/api/finance/addAsset';
