/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Expense } from '../../models/expense';

export interface FindByIdExpense$Params {
  id: number;
}

export function findByIdExpense(http: HttpClient, rootUrl: string, params: FindByIdExpense$Params, context?: HttpContext): Observable<StrictHttpResponse<Expense>> {
  const rb = new RequestBuilder(rootUrl, findByIdExpense.PATH, 'get');
  if (params) {
    rb.query('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Expense>;
    })
  );
}

findByIdExpense.PATH = '/api/finance/findExpenseById/{id}';
