/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CashFlows } from '../../models/cash-flows';

export interface FindAllCashFlows$Params {
}

export function findAllCashFlows(http: HttpClient, rootUrl: string, params?: FindAllCashFlows$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CashFlows>>> {
  const rb = new RequestBuilder(rootUrl, findAllCashFlows.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CashFlows>>;
    })
  );
}

findAllCashFlows.PATH = '/api/finance/findAllCashFlows';
