/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IncomeStatement } from '../../models/income-statement';

export interface FindAllIncomeStatements$Params {
}

export function findAllIncomeStatements(http: HttpClient, rootUrl: string, params?: FindAllIncomeStatements$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<IncomeStatement>>> {
  const rb = new RequestBuilder(rootUrl, findAllIncomeStatements.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<IncomeStatement>>;
    })
  );
}

findAllIncomeStatements.PATH = '/api/finance/findAllIncomeStatements';
