/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Expense } from '../../models/expense';

export interface FindAllExpenses$Params {
}

export function findAllExpenses(http: HttpClient, rootUrl: string, params?: FindAllExpenses$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Expense>>> {
  const rb = new RequestBuilder(rootUrl, findAllExpenses.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Expense>>;
    })
  );
}

findAllExpenses.PATH = '/api/finance/findAllExpenses';
