/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Liability } from '../../models/liability';

export interface FindAllLiabilities$Params {
}

export function findAllLiabilities(http: HttpClient, rootUrl: string, params?: FindAllLiabilities$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Liability>>> {
  const rb = new RequestBuilder(rootUrl, findAllLiabilities.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Liability>>;
    })
  );
}

findAllLiabilities.PATH = '/api/finance/findAllLiabilities';
