/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IncomeStatement } from '../../models/income-statement';

export interface FindByIdIncomeStatement$Params {
  id: number;
}

export function findByIdIncomeStatement(http: HttpClient, rootUrl: string, params: FindByIdIncomeStatement$Params, context?: HttpContext): Observable<StrictHttpResponse<IncomeStatement>> {
  const rb = new RequestBuilder(rootUrl, findByIdIncomeStatement.PATH, 'get');
  if (params) {
    rb.query('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<IncomeStatement>;
    })
  );
}

findByIdIncomeStatement.PATH = '/api/finance/findIncomeStatementById/{id}';
