/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Asset } from '../../models/asset';

export interface FindByIdAsset$Params {
  id: number;
}

export function findByIdAsset(http: HttpClient, rootUrl: string, params: FindByIdAsset$Params, context?: HttpContext): Observable<StrictHttpResponse<Asset>> {
  const rb = new RequestBuilder(rootUrl, findByIdAsset.PATH, 'get');
  if (params) {
    rb.query('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Asset>;
    })
  );
}

findByIdAsset.PATH = '/api/finance/findAssetById/{id}';
