/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CashFlows } from '../../models/cash-flows';

export interface UpdateCashFlows$Params {
  id: number;
      body: CashFlows
}

export function updateCashFlows(http: HttpClient, rootUrl: string, params: UpdateCashFlows$Params, context?: HttpContext): Observable<StrictHttpResponse<CashFlows>> {
  const rb = new RequestBuilder(rootUrl, updateCashFlows.PATH, 'put');
  if (params) {
    rb.query('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CashFlows>;
    })
  );
}

updateCashFlows.PATH = '/api/finance/updateCashFlows';
