/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CashFlows {
  amount?: number;
  categorie?: 'OPERATING' | 'INVESTING' | 'FINANCING';
  date?: string;
  description: string;
  idCashFlows?: number;
  period?: string;
  type?: 'INFLOWS' | 'OUTFLOWS';
}
