/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CashFlowStatement {
  date?: string;
  idCashFlowStatement?: number;
  netCashFlow?: number;
  period?: string;
  totalInflows?: number;
  totalOutflows?: number;
}
