/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Evaluation } from '../models/evaluation';
import { User } from '../models/user';
export interface Certification {
  description?: string;
  evaluation?: Evaluation;
  id?: number;
  issueDate?: string;
  title?: string;
  trainee?: User;
}
