/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Expense {
  amount?: number;
  date?: string;
  description: string;
  idExpense?: number;
  period?: string;
  type?: 'FIXED' | 'VARIABLE' | 'SOCIAL' | 'TAXESANDDUTIES' | 'FINANCIAL' | 'EXCEPTIONAL';
}
