/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Training } from '../models/training';
export interface Feedback {
  comment?: string;
  createdAt?: string;
  createdBy?: number;
  id?: number;
  modifiedAt?: string;
  modifiedBy?: number;
  note?: number;
  training?: Training;
}
