/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface IncomeStatement {
  date?: string;
  idIcomeStatement?: number;
  netIncome?: number;
  period?: string;
  totalExpenses?: number;
  totalRevenues?: number;
}
