/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Question {
  correctAnswer: string;
  id?: number;
  isAnswerCorrect?: boolean;
  questionText: string;
  traineeAnswer: string;
}
