/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Revenue {
  amount?: number;
  date?: string;
  idRevenue?: number;
  period?: string;
  source: string;
  type?: 'SALES' | 'OPERATING' | 'FINANCIAL' | 'EXCEPTIONAL' | 'SUBSIDIES' | 'OTHER';
}
