/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Training } from '../models/training';
export interface Skill {
  createdAt?: string;
  description?: string;
  id?: number;
  name?: string;
  skillLevel?: 'Newbie_1' | 'Beginner_2' | 'Talented_3' | 'Skilled_4' | 'Intermediate_5' | 'Skillful_6' | 'Seasoned_7' | 'Proficient_8' | 'Advanced_9' | 'Expert_10';
  skillType?: 'HARD_SKILLS' | 'SOFT_SKILLS' | 'Personal_Skills' | 'BUSINESS_SKILLS' | 'LEADERSHIP_SkillS' | 'DIGITAL_SKILLS' | 'SOCIAL_SKILLS';
  training?: Training;
  updatedAt?: string;
}
