/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TrainingRequest {
  category?: string;
  description: string;
  id?: number;
  location?: string;
  name: string;
  trainingNumber?: number;
  trainingStatus?: 'AVAILABLE' | 'UNAVAILABLE' | 'CANCELLED' | 'FORTHCOMING';
}
