/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TrainingResponse {
  category?: string;
  description?: string;
  id?: number;
  location?: string;
  name?: string;
  rate?: number;
  trainingCover?: Array<string>;
  trainingNumber?: number;
  trainingStatus?: 'AVAILABLE' | 'UNAVAILABLE' | 'CANCELLED' | 'FORTHCOMING';
}
