/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TrainingLevel } from '../models/training-level';
export interface TrainingContent {
  contentUrl: string;
  createdAt?: string;
  deletedAt?: string;
  description: string;
  id?: number;
  name: string;
  trainingLevel?: TrainingLevel;
}
