/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TrainingLevel } from '../models/training-level';
import { User } from '../models/user';
export interface TrainingSession {
  description?: string;
  endDate?: string;
  id?: number;
  startDate?: string;
  title?: string;
  trainees?: Array<User>;
  trainer?: User;
  trainingLevel?: TrainingLevel;
}
