/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Feedback } from '../models/feedback';
import { Skill } from '../models/skill';
import { TrainingLevel } from '../models/training-level';
import { User } from '../models/user';
export interface Training {
  category: string;
  createdBy?: number;
  createdDate?: string;
  description: string;
  feedbacks?: Array<Feedback>;
  id?: number;
  lastModifiedBy?: number;
  lastModifiedDate?: string;
  location: string;
  name: string;
  rate?: number;
  skills?: Array<Skill>;
  trainees?: Array<User>;
  trainer?: User;
  trainingCover?: string;
  trainingLevels?: Array<TrainingLevel>;
  trainingNumber?: number;
  trainingStatus?: 'AVAILABLE' | 'UNAVAILABLE' | 'CANCELLED' | 'FORTHCOMING';
}
