/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Certification } from '../models/certification';
import { GrantedAuthority } from '../models/granted-authority';
import { Training } from '../models/training';
import { TrainingSession } from '../models/training-session';
export interface User {
  accountLocked?: boolean;
  accountNonExpired?: boolean;
  accountNonLocked?: boolean;
  authorities?: Array<GrantedAuthority>;
  certifications?: Array<Certification>;
  createdDate?: string;
  credentialsNonExpired?: boolean;
  dateOfBirth?: string;
  email?: string;
  enabled?: boolean;
  firstname?: string;
  id?: number;
  lastModifiedDate?: string;
  lastname?: string;
  name?: string;
  password?: string;
  phoneNumber?: string;
  trainingSessions?: Array<TrainingSession>;
  trainingSessionsTrained?: Array<TrainingSession>;
  trainings?: Array<Training>;
  trainingsToTrain?: Array<Training>;
  username?: string;
}
