/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Asset {
  acquisitionDate?: string;
  categorieAsset?: 'TANGIBLE' | 'INTANGIBLE' | 'FINANCIAL' | 'INVENTORY' | 'RECEIVABLES';
  description: string;
  idAsset?: number;
  period?: string;
  typeAsset?: 'FIXED' | 'CURRENT';
  value?: number;
}
