/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BalanceSheet {
  date?: string;
  idBalanceSheet?: number;
  period?: string;
  resultatNet?: number;
  totalAssets?: number;
  totalLiabilities?: number;
}
