/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AuthenticationRequest } from './models/authentication-request';
export type { AuthenticationResponse } from './models/authentication-response';
export type { Certification } from './models/certification';
export type { Evaluation } from './models/evaluation';
export type { Feedback } from './models/feedback';
export type { FeedbackRequest } from './models/feedback-request';
export type { FeedbackResponse } from './models/feedback-response';
export type { GrantedAuthority } from './models/granted-authority';
export type { PageResponseFeedbackResponse } from './models/page-response-feedback-response';
export type { PageResponseTrainingResponse } from './models/page-response-training-response';
export type { Question } from './models/question';
export type { Quiz } from './models/quiz';
export type { RegistrationRequest } from './models/registration-request';
export type { Skill } from './models/skill';
export type { Training } from './models/training';
export type { TrainingContent } from './models/training-content';
export type { TrainingLevel } from './models/training-level';
export type { TrainingRequest } from './models/training-request';
export type { TrainingResponse } from './models/training-response';
export type { TrainingSession } from './models/training-session';
export type { User } from './models/user';
