/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Expense } from '../../models/expense';

export interface AddExpense$Params {
      body: Expense
}

export function addExpense(http: HttpClient, rootUrl: string, params: AddExpense$Params, context?: HttpContext): Observable<StrictHttpResponse<Expense>> {
  const rb = new RequestBuilder(rootUrl, addExpense.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Expense>;
    })
  );
}

addExpense.PATH = '/api/finance/addExpense';
