/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CashFlows } from '../../models/cash-flows';

export interface FindByIdCashFlows$Params {
  id: number;
}

export function findByIdCashFlows(http: HttpClient, rootUrl: string, params: FindByIdCashFlows$Params, context?: HttpContext): Observable<StrictHttpResponse<CashFlows>> {
  const rb = new RequestBuilder(rootUrl, findByIdCashFlows.PATH, 'get');
  if (params) {
    rb.query('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CashFlows>;
    })
  );
}

findByIdCashFlows.PATH = '/api/finance/findCashFlowsById/{id}';
