/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BalanceSheet } from '../../models/balance-sheet';

export interface FindAllBalanceSheets$Params {
}

export function findAllBalanceSheets(http: HttpClient, rootUrl: string, params?: FindAllBalanceSheets$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<BalanceSheet>>> {
  const rb = new RequestBuilder(rootUrl, findAllBalanceSheets.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<BalanceSheet>>;
    })
  );
}

findAllBalanceSheets.PATH = '/api/finance/findAllBalanceSheets';
