/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BalanceSheet } from '../../models/balance-sheet';

export interface FindByIdBalanceSheet$Params {
  id: number;
}

export function findByIdBalanceSheet(http: HttpClient, rootUrl: string, params: FindByIdBalanceSheet$Params, context?: HttpContext): Observable<StrictHttpResponse<BalanceSheet>> {
  const rb = new RequestBuilder(rootUrl, findByIdBalanceSheet.PATH, 'get');
  if (params) {
    rb.query('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BalanceSheet>;
    })
  );
}

findByIdBalanceSheet.PATH = '/api/finance/findBalanceSheetById/{id}';
