/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Revenue } from '../../models/revenue';

export interface FindByIdRevenue$Params {
  id: number;
}

export function findByIdRevenue(http: HttpClient, rootUrl: string, params: FindByIdRevenue$Params, context?: HttpContext): Observable<StrictHttpResponse<Revenue>> {
  const rb = new RequestBuilder(rootUrl, findByIdRevenue.PATH, 'get');
  if (params) {
    rb.query('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Revenue>;
    })
  );
}

findByIdRevenue.PATH = '/api/finance/findRevenueById/{id}';
