/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Revenue } from '../../models/revenue';

export interface UpdateRevenue$Params {
  id: number;
      body: Revenue
}

export function updateRevenue(http: HttpClient, rootUrl: string, params: UpdateRevenue$Params, context?: HttpContext): Observable<StrictHttpResponse<Revenue>> {
  const rb = new RequestBuilder(rootUrl, updateRevenue.PATH, 'put');
  if (params) {
    rb.query('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Revenue>;
    })
  );
}

updateRevenue.PATH = '/api/finance/updateRevenue';
