/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { FinanceAndAccountingProcessRestControllerService } from './services/finance-and-accounting-process-rest-controller.service';
