/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { feedbacksSaveFeedbackGet } from '../fn/operations/feedbacks-save-feedback-get';
import { FeedbacksSaveFeedbackGet$Params } from '../fn/operations/feedbacks-save-feedback-get';

@Injectable({ providedIn: 'root' })
export class ApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `feedbacksSaveFeedbackGet()` */
  static readonly FeedbacksSaveFeedbackGetPath = '/Feedbacks/saveFeedback';

  /**
   * New endpoint
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `feedbacksSaveFeedbackGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  feedbacksSaveFeedbackGet$Response(params?: FeedbacksSaveFeedbackGet$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
    return feedbacksSaveFeedbackGet(this.http, this.rootUrl, params, context);
  }

  /**
   * New endpoint
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `feedbacksSaveFeedbackGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  feedbacksSaveFeedbackGet(params?: FeedbacksSaveFeedbackGet$Params, context?: HttpContext): Observable<any> {
    return this.feedbacksSaveFeedbackGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<any>): any => r.body)
    );
  }

}
